/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BirthdayGiftsForHusbandRouteImport } from './routes/birthday-gifts-for-husband'
import { Route as GiftIdeasRouteImport } from './routes/gift-ideas'
import { Route as FindAGiftIndexRouteImport } from './routes/find-a-gift.index'
import { Route as FindAGiftResultsRouteImport } from './routes/find-a-gift.results'
import { Route as GiftsForRelationshipRouteImport } from './routes/gifts-for.$relationship'
import { Route as GiftsSlugRouteImport } from './routes/gifts.$slug'
import { Route as OccasionsOccasionRouteImport } from './routes/occasions.$occasion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayGiftsForHusbandRoute = BirthdayGiftsForHusbandRouteImport.update({
  id: '/birthday-gifts-for-husband',
  path: '/birthday-gifts-for-husband',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftIdeasRoute = GiftIdeasRouteImport.update({
  id: '/gift-ideas',
  path: '/gift-ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAGiftIndexRoute = FindAGiftIndexRouteImport.update({
  id: '/find-a-gift/',
  path: '/find-a-gift/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindAGiftResultsRoute = FindAGiftResultsRouteImport.update({
  id: '/find-a-gift/results',
  path: '/find-a-gift/results',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsForRelationshipRoute = GiftsForRelationshipRouteImport.update({
  id: '/gifts-for/$relationship',
  path: '/gifts-for/$relationship',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsSlugRoute = GiftsSlugRouteImport.update({
  id: '/gifts/$slug',
  path: '/gifts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsOccasionRoute = OccasionsOccasionRouteImport.update({
  id: '/occasions/$occasion',
  path: '/occasions/$occasion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birthday-gifts-for-husband': typeof BirthdayGiftsForHusbandRoute
  '/gift-ideas': typeof GiftIdeasRoute
  '/find-a-gift/results': typeof FindAGiftResultsRoute
  '/gifts-for/$relationship': typeof GiftsForRelationshipRoute
  '/gifts/$slug': typeof GiftsSlugRoute
  '/occasions/$occasion': typeof OccasionsOccasionRoute
  '/find-a-gift/': typeof FindAGiftIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/birthday-gifts-for-husband': typeof BirthdayGiftsForHusbandRoute
  '/gift-ideas': typeof GiftIdeasRoute
  '/find-a-gift/results': typeof FindAGiftResultsRoute
  '/gifts-for/$relationship': typeof GiftsForRelationshipRoute
  '/gifts/$slug': typeof GiftsSlugRoute
  '/occasions/$occasion': typeof OccasionsOccasionRoute
  '/find-a-gift': typeof FindAGiftIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/birthday-gifts-for-husband': typeof BirthdayGiftsForHusbandRoute
  '/gift-ideas': typeof GiftIdeasRoute
  '/find-a-gift/results': typeof FindAGiftResultsRoute
  '/gifts-for/$relationship': typeof GiftsForRelationshipRoute
  '/gifts/$slug': typeof GiftsSlugRoute
  '/occasions/$occasion': typeof OccasionsOccasionRoute
  '/find-a-gift/': typeof FindAGiftIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/birthday-gifts-for-husband'
    | '/gift-ideas'
    | '/find-a-gift/results'
    | '/gifts-for/$relationship'
    | '/gifts/$slug'
    | '/occasions/$occasion'
    | '/find-a-gift/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/birthday-gifts-for-husband'
    | '/gift-ideas'
    | '/find-a-gift/results'
    | '/gifts-for/$relationship'
    | '/gifts/$slug'
    | '/occasions/$occasion'
    | '/find-a-gift'
  id:
    | '__root__'
    | '/'
    | '/birthday-gifts-for-husband'
    | '/gift-ideas'
    | '/find-a-gift/results'
    | '/gifts-for/$relationship'
    | '/gifts/$slug'
    | '/occasions/$occasion'
    | '/find-a-gift/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BirthdayGiftsForHusbandRoute: typeof BirthdayGiftsForHusbandRoute
  GiftIdeasRoute: typeof GiftIdeasRoute
  FindAGiftResultsRoute: typeof FindAGiftResultsRoute
  GiftsForRelationshipRoute: typeof GiftsForRelationshipRoute
  GiftsSlugRoute: typeof GiftsSlugRoute
  OccasionsOccasionRoute: typeof OccasionsOccasionRoute
  FindAGiftIndexRoute: typeof FindAGiftIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday-gifts-for-husband': {
      id: '/birthday-gifts-for-husband'
      path: '/birthday-gifts-for-husband'
      fullPath: '/birthday-gifts-for-husband'
      preLoaderRoute: typeof BirthdayGiftsForHusbandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-ideas': {
      id: '/gift-ideas'
      path: '/gift-ideas'
      fullPath: '/gift-ideas'
      preLoaderRoute: typeof GiftIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-gift/': {
      id: '/find-a-gift/'
      path: '/find-a-gift'
      fullPath: '/find-a-gift/'
      preLoaderRoute: typeof FindAGiftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-gift/results': {
      id: '/find-a-gift/results'
      path: '/find-a-gift/results'
      fullPath: '/find-a-gift/results'
      preLoaderRoute: typeof FindAGiftResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts-for/$relationship': {
      id: '/gifts-for/$relationship'
      path: '/gifts-for/$relationship'
      fullPath: '/gifts-for/$relationship'
      preLoaderRoute: typeof GiftsForRelationshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts/$slug': {
      id: '/gifts/$slug'
      path: '/gifts/$slug'
      fullPath: '/gifts/$slug'
      preLoaderRoute: typeof GiftsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/$occasion': {
      id: '/occasions/$occasion'
      path: '/occasions/$occasion'
      fullPath: '/occasions/$occasion'
      preLoaderRoute: typeof OccasionsOccasionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BirthdayGiftsForHusbandRoute: BirthdayGiftsForHusbandRoute,
  GiftIdeasRoute: GiftIdeasRoute,
  FindAGiftResultsRoute: FindAGiftResultsRoute,
  GiftsForRelationshipRoute: GiftsForRelationshipRoute,
  GiftsSlugRoute: GiftsSlugRoute,
  OccasionsOccasionRoute: OccasionsOccasionRoute,
  FindAGiftIndexRoute: FindAGiftIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
